// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpqavxmfknxqsyrqyhxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcWF2eG1ma254cXN5cnF5aHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MTQ5NzEsImV4cCI6MjA3NzI5MDk3MX0.4qnHC5R5TBug4H9mOWh1PFkEhv1BJjIzD0PzUWKava4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});